@startuml
'https://plantuml.com/class-diagram

'克隆对象
PrototypeObject "n" --|> "1" Prototype

'实现
Prototype ..|> Serializable
Prototype ..|> Cloneable

'生成类
class PrototypeObject {
    #Object clone() throws CloneNotSupportedException
    +Object serialize()
}

'原型类
class Prototype {
    #Object clone() throws CloneNotSupportedException
    +Object serialize()
}

'序列化接口
interface Serializable {
}

'clone接口
interface Cloneable {
}

@enduml